<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project [
<!ELEMENT project (circuit+)>
<!ATTLIST project
	main-circuit CDATA #IMPLIED
>
<!ELEMENT circuit
        (circuit*,
	(and|andthree|or|orthree|xor|neg|nand|nor|switch|bulb|label|zero|one|jk|led|clock|nib|wire|plugin|card|chip|bus|bundler|switch_bank|bulb_bank|connector|abscircuit)*)>
<!ATTLIST circuit
        name CDATA #REQUIRED
        freeze CDATA #IMPLIED
        appsecure CDATA #IMPLIED
        chipModel CDATA #IMPLIED>
<!ELEMENT and (coords?, parent-of*, bundle*)*>
<!ATTLIST and
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>
<!ELEMENT andthree (coords?, parent-of*, bundle*)*>
<!ATTLIST andthree
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>
<!ELEMENT or (coords?, parent-of*, bundle*)*>
<!ATTLIST or
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>        
<!ELEMENT orthree (coords?, parent-of*, bundle*)*>
<!ATTLIST orthree
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>        
<!ELEMENT xor (coords?, parent-of*, bundle*)*>
<!ATTLIST xor
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>
<!ELEMENT neg (coords?, parent-of*, bundle*)*>
<!ATTLIST neg
        id CDATA #REQUIRED
        mult CDATA #IMPLIED>
<!ELEMENT nand (coords?, parent-of*, bundle*)*>
<!ATTLIST nand
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>
<!ELEMENT nor (coords?, parent-of*, bundle*)*>
<!ATTLIST nor
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>
<!ELEMENT jk (coords?, parent-of*, bundle*)*>
<!ATTLIST jk
        id CDATA #REQUIRED
        trigger CDATA #IMPLIED
        mult CDATA #IMPLIED>        
<!ELEMENT led (coords?, parent-of*, bundle*)*>
<!ATTLIST led
        id CDATA #REQUIRED
        order CDATA "-1"
        mult CDATA #IMPLIED>        
<!ELEMENT zero (coords?, parent-of*, bundle*)*>
<!ATTLIST zero
        id CDATA #REQUIRED>
<!ELEMENT one (coords?, parent-of*, bundle*)*>
<!ATTLIST one
        id CDATA #REQUIRED>
<!ELEMENT switch (coords?, parent-of*, bundle*)*>
<!ATTLIST switch
        id CDATA #REQUIRED
        number CDATA #REQUIRED
		label CDATA #IMPLIED>
<!ELEMENT bulb (coords?, parent-of*, bundle*)*>
<!ATTLIST bulb
    	id CDATA #REQUIRED
    	number CDATA #REQUIRED
		label CDATA #IMPLIED>
<!ELEMENT label (coords?, parent-of*, text)*>
<!ATTLIST label
        id CDATA #REQUIRED
		size CDATA #REQUIRED
		style CDATA #REQUIRED
		color CDATA #REQUIRED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT clock (coords?, parent-of*, bundle*)>
<!ATTLIST clock
        id CDATA #REQUIRED
		speed CDATA #REQUIRED>
<!ELEMENT nib (coords?, parent-of*, bundle*)*>
<!ATTLIST nib
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        mult CDATA #IMPLIED>        
<!ELEMENT wire (coords?, parent-of*, bundle*)*>
<!ATTLIST wire
        id CDATA #REQUIRED
		direction CDATA #REQUIRED
        mult CDATA #IMPLIED>
<!ELEMENT abscircuit (coords?, parent-of*, bundle*)*>
<!ATTLIST abscircuit
        id CDATA #REQUIRED
		base CDATA #REQUIRED>
<!ELEMENT card (coords?, parent-of*, bundle*)*>
<!ATTLIST card
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
		base CDATA #REQUIRED>	
<!ELEMENT chip (coords?, parent-of*, bundle*)*>
<!ATTLIST chip
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        inDegree CDATA #REQUIRED
        outDegree CDATA #REQUIRED
		base CDATA #REQUIRED>
<!ELEMENT plugin (properties*, coords?, parent-of*, bundle*)*>
<!ATTLIST plugin
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
		base CDATA #REQUIRED
		mode CDATA "0"
		data CDATA "0"
		initString CDATA "">
<!ELEMENT properties (entry*)>
<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry
		key CDATA #REQUIRED>
<!ELEMENT bus (coords?, parent-of*, bundle*)*>
<!ATTLIST bus
        id CDATA #REQUIRED
        width CDATA #REQUIRED
        mode (ONE_TO_ONE|AND_IN|OR_IN) "ONE_TO_ONE"
        in CDATA "1"
        out CDATA "1"
        mult CDATA #IMPLIED>        
<!ELEMENT bundler (coords?, parent-of*, bundle*)*>
<!ATTLIST bundler
        id CDATA #REQUIRED
        triggerpair CDATA #IMPLIED
        width CDATA #REQUIRED
        in CDATA #REQUIRED
        out CDATA #REQUIRED
        name CDATA #IMPLIED
        mode (BUNDLER|BIT_MULTIPLIER|BIT_COLLECTOR|NAMED_SOURCE|NAMED_SINK) "BUNDLER">
<!ELEMENT switch_bank  (coords?, parent-of*, bundle*, pinLabel*)*>
<!ATTLIST switch_bank
		id CDATA #REQUIRED
		number CDATA "0"
		fatPin (true|false) "false"
		label CDATA #IMPLIED
		size CDATA #REQUIRED>
<!ELEMENT bulb_bank  (coords?, parent-of*, bundle*, pinLabel*)*>
<!ATTLIST bulb_bank
		id CDATA #REQUIRED
		number CDATA "0"
		fatPin (true|false) "false"
		label CDATA #IMPLIED
		size CDATA #REQUIRED>
<!ELEMENT connector (legs, parent-of*, bundle*, pinLabel*)*>
<!ATTLIST connector
		id CDATA #REQUIRED
		mult CDATA #IMPLIED>
<!ELEMENT legs (leg*)>
<!ELEMENT leg EMPTY>
<!ATTLIST leg
		idx CDATA #REQUIRED
		x CDATA #REQUIRED
		y CDATA #REQUIRED>
<!ELEMENT pinLabel EMPTY>
<!ATTLIST pinLabel
		id CDATA #REQUIRED
		text CDATA #REQUIRED>
<!ELEMENT coords EMPTY>
<!ATTLIST coords
		x CDATA #REQUIRED
		y CDATA #REQUIRED>
<!ELEMENT parent-of (#PCDATA)>
<!ATTLIST parent-of
        pindex CDATA #REQUIRED
        cindex CDATA #REQUIRED
        mult CDATA "1">
<!ELEMENT bundle (bundle_pair)*>
<!ELEMENT bundle_pair (#PCDATA)>
<!ATTLIST bundle_pair
        pindex CDATA #REQUIRED
        cindex CDATA #REQUIRED>]>
<project main-circuit="Multiplexor">
	<circuit name="2to1mux">
		<switch id="2to1mux:Switch0" number="0" label="I0">
			<coords x="50" y="20"/>
			<parent-of pindex="0" cindex="0">2to1mux:And1</parent-of>
		</switch>
		<switch id="2to1mux:Switch1" number="1" label="I1">
			<coords x="50" y="90"/>
			<parent-of pindex="0" cindex="0">2to1mux:And2</parent-of>
		</switch>
		<switch id="2to1mux:Switch2" number="2" label="select">
			<coords x="50" y="160"/>
			<parent-of pindex="0" cindex="0">2to1mux:Connector1</parent-of>
		</switch>
		<bulb id="2to1mux:Bulb3" number="3" label="out">
			<coords x="350" y="70"/>
		</bulb>
		<and id="2to1mux:And1">
			<coords x="190" y="30"/>
			<parent-of pindex="2" cindex="0">2to1mux:Or1</parent-of>
		</and>
		<and id="2to1mux:And2">
			<coords x="190" y="100"/>
			<parent-of pindex="2" cindex="1">2to1mux:Or1</parent-of>
		</and>
		<or id="2to1mux:Or1">
			<coords x="280" y="70"/>
			<parent-of pindex="2" cindex="0">2to1mux:Bulb3</parent-of>
		</or>
		<neg id="2to1mux:Neg1">
			<coords x="130" y="50"/>
			<parent-of pindex="1" cindex="1">2to1mux:And1</parent-of>
		</neg>
		<connector id="2to1mux:Connector1">
			<legs>
				<leg idx="0" x="115" y="175"/>
				<leg idx="1" x="115" y="125"/>
				<leg idx="2" x="115" y="65"/>
			</legs>
			<parent-of pindex="2" cindex="0">2to1mux:Neg1</parent-of>
			<parent-of pindex="1" cindex="1">2to1mux:And2</parent-of>
		</connector>
	</circuit>
	<circuit name="4to1mux">
		<switch id="4to1mux:Switch0" number="0" label="I0">
			<coords x="50" y="20"/>
			<parent-of pindex="0" cindex="0">4to1mux:2to1mux1</parent-of>
		</switch>
		<switch id="4to1mux:Switch1" number="1" label="I1">
			<coords x="50" y="70"/>
			<parent-of pindex="0" cindex="1">4to1mux:2to1mux1</parent-of>
		</switch>
		<switch id="4to1mux:Switch2" number="2" label="I2">
			<coords x="50" y="130"/>
			<parent-of pindex="0" cindex="0">4to1mux:2to1mux2</parent-of>
		</switch>
		<switch id="4to1mux:Switch3" number="3" label="I3">
			<coords x="50" y="190"/>
			<parent-of pindex="0" cindex="1">4to1mux:2to1mux2</parent-of>
		</switch>
		<switch id="4to1mux:Switch4" number="4" label="S1">
			<coords x="50" y="260"/>
			<parent-of pindex="0" cindex="0">4to1mux:Connector1</parent-of>
		</switch>
		<switch id="4to1mux:Switch5" number="5" label="S0">
			<coords x="50" y="320"/>
			<parent-of pindex="0" cindex="0">4to1mux:Connector2</parent-of>
		</switch>
		<bulb id="4to1mux:Bulb6" number="6" label="out">
			<coords x="490" y="80"/>
		</bulb>
		<card id="4to1mux:2to1mux1" base="2to1mux">
			<coords x="170" y="50"/>
			<parent-of pindex="3" cindex="0">4to1mux:2to1mux3</parent-of>
		</card>
		<card id="4to1mux:2to1mux2" base="2to1mux">
			<coords x="170" y="160"/>
			<parent-of pindex="3" cindex="1">4to1mux:2to1mux3</parent-of>
		</card>
		<card id="4to1mux:2to1mux3" base="2to1mux">
			<coords x="340" y="90"/>
			<parent-of pindex="3" cindex="0">4to1mux:Bulb6</parent-of>
		</card>
		<connector id="4to1mux:Connector1">
			<legs>
				<leg idx="0" x="105" y="275"/>
				<leg idx="1" x="325" y="275"/>
				<leg idx="2" x="325" y="115"/>
			</legs>
			<parent-of pindex="2" cindex="2">4to1mux:2to1mux3</parent-of>
		</connector>
		<connector id="4to1mux:Connector2">
			<legs>
				<leg idx="0" x="145" y="335"/>
				<leg idx="1" x="145" y="185"/>
				<leg idx="2" x="145" y="75"/>
			</legs>
			<parent-of pindex="2" cindex="2">4to1mux:2to1mux1</parent-of>
			<parent-of pindex="1" cindex="2">4to1mux:2to1mux2</parent-of>
		</connector>
	</circuit>
	<circuit name="4bit2to1mux">
		<switch_bank id="4bit2to1mux:Switch_bank1" size="4" fatPin="true" number="0" label="A0">
			<coords x="140" y="130"/>
			<parent-of pindex="0" cindex="0" mult="4">4bit2to1mux:And4</parent-of>
		</switch_bank>
		<bundler id="4bit2to1mux:Bundler1" width="4" in="1" out="4" mode="BIT_MULTIPLIER">
			<coords x="230" y="490"/>
			<parent-of pindex="1" cindex="4" mult="4">4bit2to1mux:And3</parent-of>
		</bundler>
		<and id="4bit2to1mux:And3" mult="4">
			<coords x="330" y="340"/>
			<parent-of pindex="8" cindex="4" mult="4">4bit2to1mux:Connector3</parent-of>
		</and>
		<and id="4bit2to1mux:And4" mult="4">
			<coords x="330" y="200"/>
			<parent-of pindex="8" cindex="4" mult="4">4bit2to1mux:Connector4</parent-of>
		</and>
		<or id="4bit2to1mux:Or3" mult="4">
			<coords x="430" y="290"/>
			<parent-of pindex="8" cindex="0" mult="4">4bit2to1mux:Bulb_bank20</parent-of>
		</or>
		<connector id="4bit2to1mux:Connector2">
			<legs>
				<leg idx="0" x="125" y="495"/>
				<leg idx="1" x="145" y="495"/>
				<leg idx="2" x="145" y="445"/>
			</legs>
			<parent-of pindex="1" cindex="0">4bit2to1mux:Bundler1</parent-of>
			<parent-of pindex="2" cindex="0">4bit2to1mux:Neg3</parent-of>
		</connector>
		<bundler id="4bit2to1mux:Bundler2" width="4" in="1" out="4" mode="BIT_MULTIPLIER">
			<coords x="200" y="440"/>
			<parent-of pindex="1" cindex="4" mult="4">4bit2to1mux:And4</parent-of>
		</bundler>
		<neg id="4bit2to1mux:Neg3">
			<coords x="160" y="430"/>
			<parent-of pindex="1" cindex="0">4bit2to1mux:Bundler2</parent-of>
		</neg>
		<connector id="4bit2to1mux:Connector3" mult="4">
			<legs>
				<leg idx="0" x="415" y="325"/>
				<leg idx="1" x="415" y="365"/>
				<leg idx="2" x="415" y="415"/>
			</legs>
			<parent-of pindex="0" cindex="4" mult="4">4bit2to1mux:Or3</parent-of>
		</connector>
		<connector id="4bit2to1mux:Connector4" mult="4">
			<legs>
				<leg idx="0" x="415" y="165"/>
				<leg idx="1" x="415" y="225"/>
				<leg idx="2" x="415" y="305"/>
			</legs>
			<parent-of pindex="8" cindex="0" mult="4">4bit2to1mux:Or3</parent-of>
		</connector>
		<switch_bank id="4bit2to1mux:Switch_bank20" size="4" fatPin="true" number="4" label="A1">
			<coords x="140" y="270"/>
			<parent-of pindex="0" cindex="0" mult="4">4bit2to1mux:And3</parent-of>
		</switch_bank>
		<switch id="4bit2to1mux:Switch8" number="8" label="select">
			<coords x="30" y="480"/>
			<parent-of pindex="0" cindex="0">4bit2to1mux:Connector2</parent-of>
		</switch>
		<bulb_bank id="4bit2to1mux:Bulb_bank20" size="4" fatPin="true" number="9" label="output">
			<coords x="530" y="280"/>
		</bulb_bank>
	</circuit>
	<circuit name="8bit2to1mux">
		<switch_bank id="8bit2to1mux:Switch_bank1" size="8" fatPin="true" number="0" label="I0">
			<coords x="50" y="10"/>
			<parent-of pindex="0" cindex="0">8bit2to1mux:2to1mux1</parent-of>
			<parent-of pindex="1" cindex="0">8bit2to1mux:2to1mux2</parent-of>
			<parent-of pindex="2" cindex="0">8bit2to1mux:2to1mux3</parent-of>
			<parent-of pindex="3" cindex="0">8bit2to1mux:2to1mux4</parent-of>
			<parent-of pindex="4" cindex="0">8bit2to1mux:2to1mux5</parent-of>
			<parent-of pindex="5" cindex="0">8bit2to1mux:2to1mux6</parent-of>
			<parent-of pindex="6" cindex="0">8bit2to1mux:2to1mux7</parent-of>
			<parent-of pindex="7" cindex="0">8bit2to1mux:2to1mux8</parent-of>
		</switch_bank>
		<switch_bank id="8bit2to1mux:Switch_bank10" size="8" fatPin="true" number="8" label="I1">
			<coords x="50" y="230"/>
			<parent-of pindex="0" cindex="1">8bit2to1mux:2to1mux1</parent-of>
			<parent-of pindex="1" cindex="1">8bit2to1mux:2to1mux2</parent-of>
			<parent-of pindex="2" cindex="1">8bit2to1mux:2to1mux3</parent-of>
			<parent-of pindex="3" cindex="1">8bit2to1mux:2to1mux4</parent-of>
			<parent-of pindex="4" cindex="1">8bit2to1mux:2to1mux5</parent-of>
			<parent-of pindex="5" cindex="1">8bit2to1mux:2to1mux6</parent-of>
			<parent-of pindex="6" cindex="1">8bit2to1mux:2to1mux7</parent-of>
			<parent-of pindex="7" cindex="1">8bit2to1mux:2to1mux8</parent-of>
		</switch_bank>
		<card id="8bit2to1mux:2to1mux1" base="2to1mux">
			<coords x="248" y="49"/>
			<parent-of pindex="3" cindex="0">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux2" base="2to1mux">
			<coords x="258" y="89"/>
			<parent-of pindex="3" cindex="1">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux3" base="2to1mux">
			<coords x="270" y="130"/>
			<parent-of pindex="3" cindex="2">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux4" base="2to1mux">
			<coords x="278" y="169"/>
			<parent-of pindex="3" cindex="3">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux5" base="2to1mux">
			<coords x="288" y="209"/>
			<parent-of pindex="3" cindex="4">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux6" base="2to1mux">
			<coords x="298" y="249"/>
			<parent-of pindex="3" cindex="5">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux7" base="2to1mux">
			<coords x="308" y="289"/>
			<parent-of pindex="3" cindex="6">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<card id="8bit2to1mux:2to1mux8" base="2to1mux">
			<coords x="317" y="326"/>
			<parent-of pindex="3" cindex="7">8bit2to1mux:Bulb_bank1</parent-of>
		</card>
		<switch id="8bit2to1mux:Switch16" number="16" label="select">
			<coords x="60" y="490"/>
			<parent-of pindex="0" cindex="0">8bit2to1mux:Connector1</parent-of>
		</switch>
		<bulb_bank id="8bit2to1mux:Bulb_bank1" size="8" fatPin="true" number="17" label="output">
			<coords x="500" y="10"/>
		</bulb_bank>
		<connector id="8bit2to1mux:Connector1">
			<legs>
				<leg idx="0" x="125" y="505"/>
				<leg idx="1" x="125" y="355"/>
				<leg idx="2" x="125" y="315"/>
				<leg idx="3" x="125" y="275"/>
				<leg idx="4" x="125" y="235"/>
				<leg idx="5" x="125" y="195"/>
				<leg idx="6" x="125" y="155"/>
				<leg idx="7" x="125" y="115"/>
				<leg idx="8" x="125" y="75"/>
			</legs>
			<parent-of pindex="1" cindex="2">8bit2to1mux:2to1mux8</parent-of>
			<parent-of pindex="2" cindex="2">8bit2to1mux:2to1mux7</parent-of>
			<parent-of pindex="3" cindex="2">8bit2to1mux:2to1mux6</parent-of>
			<parent-of pindex="4" cindex="2">8bit2to1mux:2to1mux5</parent-of>
			<parent-of pindex="5" cindex="2">8bit2to1mux:2to1mux4</parent-of>
			<parent-of pindex="6" cindex="2">8bit2to1mux:2to1mux3</parent-of>
			<parent-of pindex="7" cindex="2">8bit2to1mux:2to1mux2</parent-of>
			<parent-of pindex="8" cindex="2">8bit2to1mux:2to1mux1</parent-of>
		</connector>
	</circuit>
	<circuit name="Multiplexor">
		<card id="Multiplexor:8bit2to1mux2" base="8bit2to1mux">
			<coords x="280" y="140"/>
			<parent-of pindex="17" cindex="0" mult="8">Multiplexor:Bulb_bank1</parent-of>
		</card>
		<switch_bank id="Multiplexor:Switch_bank1" size="8" fatPin="false" number="0">
			<coords x="20" y="10"/>
			<parent-of pindex="0" cindex="0" mult="8">Multiplexor:8bit2to1mux2</parent-of>
		</switch_bank>
		<switch_bank id="Multiplexor:Switch_bank10" size="8" fatPin="false" number="8">
			<coords x="20" y="230"/>
			<parent-of pindex="0" cindex="8" mult="8">Multiplexor:8bit2to1mux2</parent-of>
		</switch_bank>
		<switch id="Multiplexor:Switch16" number="16">
			<coords x="190" y="280"/>
			<parent-of pindex="0" cindex="16">Multiplexor:8bit2to1mux2</parent-of>
		</switch>
		<bulb_bank id="Multiplexor:Bulb_bank1" size="8" fatPin="false" number="17">
			<coords x="540" y="70"/>
		</bulb_bank>
	</circuit>
	<circuit name="16to1mux">
		<card id="16to1mux:4to1mux1" base="4to1mux">
			<coords x="200" y="90"/>
			<parent-of pindex="6" cindex="0">16to1mux:4to1mux5</parent-of>
		</card>
		<card id="16to1mux:4to1mux2" base="4to1mux">
			<coords x="180" y="170"/>
			<parent-of pindex="6" cindex="1">16to1mux:4to1mux5</parent-of>
		</card>
		<card id="16to1mux:4to1mux3" base="4to1mux">
			<coords x="180" y="250"/>
			<parent-of pindex="6" cindex="2">16to1mux:4to1mux5</parent-of>
		</card>
		<card id="16to1mux:4to1mux4" base="4to1mux">
			<coords x="200" y="330"/>
			<parent-of pindex="6" cindex="3">16to1mux:4to1mux5</parent-of>
		</card>
		<card id="16to1mux:4to1mux5" base="4to1mux">
			<coords x="420" y="190"/>
			<parent-of pindex="6" cindex="0">16to1mux:Bulb20</parent-of>
		</card>
		<switch_bank id="16to1mux:Switch_bank1" size="16" fatPin="true" number="0" label="input">
			<coords x="40" y="30"/>
			<parent-of pindex="0" cindex="0">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="1" cindex="1">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="2" cindex="2">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="3" cindex="3">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="4" cindex="0">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="5" cindex="1">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="6" cindex="2">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="7" cindex="3">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="8" cindex="0">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="9" cindex="1">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="10" cindex="2">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="11" cindex="3">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="12" cindex="0">16to1mux:4to1mux4</parent-of>
			<parent-of pindex="13" cindex="1">16to1mux:4to1mux4</parent-of>
			<parent-of pindex="14" cindex="2">16to1mux:4to1mux4</parent-of>
			<parent-of pindex="15" cindex="3">16to1mux:4to1mux4</parent-of>
		</switch_bank>
		<switch_bank id="16to1mux:Switch_bank19" size="4" fatPin="true" number="16" label="select">
			<coords x="40" y="430"/>
			<parent-of pindex="0" cindex="0">16to1mux:Connector1</parent-of>
			<parent-of pindex="1" cindex="0">16to1mux:Connector2</parent-of>
			<parent-of pindex="2" cindex="0">16to1mux:Connector3</parent-of>
			<parent-of pindex="3" cindex="0">16to1mux:Connector4</parent-of>
		</switch_bank>
		<bulb id="16to1mux:Bulb20" number="20" label="out">
			<coords x="610" y="180"/>
		</bulb>
		<connector id="16to1mux:Connector1">
			<legs>
				<leg idx="0" x="115" y="485"/>
				<leg idx="1" x="325" y="485"/>
				<leg idx="2" x="325" y="235"/>
			</legs>
			<parent-of pindex="2" cindex="4">16to1mux:4to1mux5</parent-of>
		</connector>
		<connector id="16to1mux:Connector2">
			<legs>
				<leg idx="0" x="115" y="505"/>
				<leg idx="1" x="345" y="505"/>
				<leg idx="2" x="345" y="245"/>
			</legs>
			<parent-of pindex="2" cindex="5">16to1mux:4to1mux5</parent-of>
		</connector>
		<connector id="16to1mux:Connector3">
			<legs>
				<leg idx="0" x="125" y="525"/>
				<leg idx="1" x="125" y="375"/>
				<leg idx="2" x="125" y="295"/>
				<leg idx="3" x="125" y="215"/>
				<leg idx="4" x="125" y="135"/>
			</legs>
			<parent-of pindex="4" cindex="4">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="3" cindex="4">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="2" cindex="4">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="1" cindex="4">16to1mux:4to1mux4</parent-of>
		</connector>
		<connector id="16to1mux:Connector4">
			<legs>
				<leg idx="0" x="155" y="545"/>
				<leg idx="1" x="155" y="395"/>
				<leg idx="2" x="155" y="305"/>
				<leg idx="3" x="155" y="225"/>
				<leg idx="4" x="155" y="145"/>
			</legs>
			<parent-of pindex="4" cindex="5">16to1mux:4to1mux1</parent-of>
			<parent-of pindex="3" cindex="5">16to1mux:4to1mux2</parent-of>
			<parent-of pindex="2" cindex="5">16to1mux:4to1mux3</parent-of>
			<parent-of pindex="1" cindex="5">16to1mux:4to1mux4</parent-of>
		</connector>
	</circuit>
</project>
